# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/lib/modules/6.6.87.2-microsoft-standard-WSL2" = {
    device = "none";
    fsType = "overlay";
  };

  fileSystems."/mnt/wsl" = {
    device = "none";
    fsType = "tmpfs";
  };

  fileSystems."/usr/lib/wsl/drivers" = {
    device = "drivers";
    fsType = "9p";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/562b76be-0380-4de1-82f0-1653810e153c";
    fsType = "ext4";
  };

  # WSL-specific filesystems - commented out to avoid mount errors
  # fileSystems."/mnt/wslg" =
  #   { device = "none";
  #     fsType = "tmpfs";
  #   };

  # fileSystems."/mnt/wslg/distro" =
  #   { device = null;
  #     fsType = "none";
  #     options = [ "bind" ];
  #   };

  # fileSystems."/usr/lib/wsl/lib" =
  #   { device = "none";
  #     fsType = "overlay";
  #   };

  # fileSystems."/tmp/.X11-unix" =
  #   { device = "/mnt/wslg/.X11-unix";
  #     fsType = "none";
  #     options = [ "bind" ];
  #   };

  # fileSystems."/mnt/wslg/doc" =
  #   { device = "none";
  #     fsType = "overlay";
  #   };

  fileSystems."/mnt/c" = {
    device = "C:\134";
    fsType = "9p";
  };

  fileSystems."/mnt/wslg/run/user/1000" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/4d1021cc-12c2-4dfd-96b1-e1c216e89ae1"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
