name: "Cachix"
on:
  pull_request:
  push:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: arifinoid-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix flake check
    - run: |
        nix build .#wsl-arifinoid --json | jq -r '.[].outputs | to_entries[].value' | cachix push arifinoid-nix